user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        location /api/cabinbookings/days {
            proxy_pass http://cabinbookings:3011/days;
        }
        location /api/electricity/current {
            proxy_pass http://electricity:3016/solar/current;
        }
        
        # Simplest possible approach for climate API
        location /api/indoor {
            # Without a trailing slash in location but with one in proxy_pass
            proxy_pass http://climateapi:5011/;
        }
        
        # Handle direct device access (without any rewriting)
        location ~ ^/api/dev_ {
            proxy_pass http://climateapi:5011/;
        }
        
        location /api {
            proxy_pass http://api:6001/api;
        }
        location / {
            proxy_pass http://homeapp73:3000;
        }
   }
}